kind: pipeline
type: docker
name: deploy-client

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/alisher134/tarih-client
      tags: latest
      username: alisher134
      password:
        from_secret: GH_PACKAGES_TOKEN
      dockerfile: Dockerfile

  - name: deploy-to-server
    image: appleboy/drone-ssh
    settings:
      host: 89.126.200.145
      username: root
      key:
        from_secret: SSH_KEY
      script:
        - cd /root/tarih/tarih-client
        - git pull origin main
        - docker compose -f docker-compose.prod.yml pull client
        - docker compose -f docker-compose.prod.yml up -d client

trigger:
  branch:
    - main
  event:
    - push
